# Generated by Django 5.2.6 on 2025-09-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_cleaninglog_maid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maid',
            name='break_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maid',
            name='shift_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maid',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maid',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
