# Generated by Django 5.2.6 on 2025-09-21 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('maid_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('profile_info', models.TextField(blank=True, null=True)),
                ('shift_day', models.CharField(max_length=20)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('break_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaidStat',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_rooms_cleaned', models.IntegerField(default=0)),
                ('avg_rooms_per_shift', models.FloatField(default=0)),
                ('avg_time_per_room', models.FloatField(default=0)),
                ('working_hours', models.FloatField(default=0)),
                ('active_cleaning_hours', models.FloatField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('tasks_incomplete', models.IntegerField(default=0)),
                ('emergency_tasks_handled', models.IntegerField(default=0)),
                ('battery_changes_performed', models.IntegerField(default=0)),
                ('on_time_shift_attendance', models.FloatField(default=0)),
                ('break_usage', models.FloatField(default=0)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.maid')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('do_not_disturb', 'Do Not Disturb'), ('cleaning_in_progress', 'Cleaning in Progress'), ('emergency_clean', 'Emergency Clean'), ('dirty', 'Dirty')], max_length=30)),
                ('battery_indicator', models.IntegerField(default=100)),
                ('battery_last_checked', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.floor')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatusLog',
            fields=[
                ('room_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('do_not_disturb', 'Do Not Disturb'), ('cleaning_in_progress', 'Cleaning in Progress'), ('emergency_clean', 'Emergency Clean')], max_length=30)),
                ('changed_by', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('assigned_time', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('battery_change_required', models.BooleanField(default=False)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.maid')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.TextField(blank=True, null=True)),
                ('assigned_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by_admin', models.BooleanField(default=False)),
                ('battery_changed', models.BooleanField(default=False)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.maid')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.task')),
            ],
        ),
    ]
