# Generated by Django 5.2.6 on 2025-09-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='password_hash',
        ),
    ]
