# Generated by Django 5.2.6 on 2025-09-21 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_admin_email_remove_admin_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaninglog',
            name='maid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.maid'),
        ),
    ]
