# Generated by Django 5.2.6 on 2025-10-31 18:28

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_maid_break_minutes_alter_maid_shift_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maid',
            name='shift_day',
        ),
        migrations.AddField(
            model_name='maid',
            name='shift_days',
            field=models.JSONField(blank=True, default=list, validators=[hotel.models.validate_shift_days]),
        ),
    ]
