# Generated by Django 5.2.6 on 2025-11-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_maid_shift_day_maid_shift_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('clean', 'Clean'), ('do_not_disturb', 'Do Not Disturb'), ('cleaning_in_progress', 'Cleaning in Progress'), ('emergency_clean', 'Emergency Clean'), ('dirty', 'Dirty')], default='clean', max_length=30),
        ),
    ]
