# Generated by Django 5.2.6 on 2025-11-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pos_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='pos_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
