# Generated by Django 5.2.6 on 2025-11-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_pos_x_room_pos_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
